name: aligntracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  delightful_toast: ^1.1.0
  image_picker: ^1.1.2
  mime: ^1.0.0
  http_parser: ^4.0.0
  google_nav_bar: ^5.0.7
  slide_to_act: ^2.0.2
  flutter_background_service: ^5.0.10
  geolocator: ^13.0.1
  path_provider: ^2.0.9
  liquid_pull_to_refresh: ^3.0.1
  permission_handler: ^10.2.0
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
